#!/usr/bin/env python3
"""Run every claims/<ID>/check.py and print the PASS table.

    python claims/run_all.py              # all claims
    python claims/run_all.py K5 I.10      # claims whose ID starts with any of the arguments
    python claims/run_all.py -j 4         # four checks in parallel (each check is single-threaded)

A claim is certified iff its check.py exits 0 and prints "PASS <ID>". The table (ID, status, wall time, title) is
printed at the end and written to claims/STATUS.md; full outputs go to claims/<ID>/check_output.txt.
"""

from __future__ import annotations

import argparse
import concurrent.futures as cf
import os
import pathlib
import re
import subprocess
import sys
import time

ROOT = pathlib.Path(__file__).resolve().parents[1]
CLAIMS = ROOT / "claims"


def claim_dirs(prefixes):
    def key(p):
        parts = re.split(r"[.]", p.name)
        return (parts[0], [int(x) if x.isdigit() else x for x in parts[1:]])

    dirs = sorted((d for d in CLAIMS.iterdir() if (d / "check.py").exists()), key=key)
    if prefixes:
        dirs = [d for d in dirs if any(d.name.startswith(p) for p in prefixes)]
    return dirs


def title(d):
    first = (d / "claim.md").read_text().splitlines()[0] if (d / "claim.md").exists() else ""
    return re.sub(r"^#\s*\S+\s*[—-]\s*", "", first).strip()


def run_one(d):
    env = dict(os.environ, OPENBLAS_NUM_THREADS="1", OMP_NUM_THREADS="1", MKL_NUM_THREADS="1", PYTHONHASHSEED="0")
    t0 = time.time()
    r = subprocess.run([sys.executable, str(d / "check.py")], capture_output=True, text=True, cwd=ROOT, env=env)
    dt = time.time() - t0
    out = r.stdout + ("\n--- stderr ---\n" + r.stderr if r.stderr.strip() else "")
    (d / "check_output.txt").write_text(out)
    ok = r.returncode == 0 and f"PASS {d.name}" in r.stdout
    return d.name, ok, dt


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("prefixes", nargs="*")
    ap.add_argument("-j", "--jobs", type=int, default=1)
    a = ap.parse_args()
    dirs = claim_dirs(a.prefixes)
    results = {}
    with cf.ThreadPoolExecutor(max_workers=a.jobs) as ex:
        for name, ok, dt in ex.map(run_one, dirs):
            results[name] = (ok, dt)
            print(f"{'PASS' if ok else 'FAIL'} {name} ({dt:.0f} s)", flush=True)
    rows = ["| ID | status | time (s) | claim |", "|---|---|---|---|"]
    for d in dirs:
        ok, dt = results[d.name]
        rows.append(f"| [{d.name}]({d.name}/claim.md) | {'PASS' if ok else 'FAIL'} | {dt:.0f} | {title(d)} |")
    table = "\n".join(rows)
    print("\n" + table)
    n_ok = sum(ok for ok, _ in results.values())
    print(f"\n{n_ok}/{len(results)} PASS")
    if not a.prefixes:
        (CLAIMS / "STATUS.md").write_text(
            "# Claim status\n\nGenerated by `python claims/run_all.py` (`make check`).\n\n" + table + "\n"
        )
    sys.exit(0 if n_ok == len(results) else 1)


if __name__ == "__main__":
    main()
