"""Linear representations of the lattice symmetry group on spaces of same-parity patterns, and character sums.

A signed-permutation symmetry (g, s) of K (``masspairing.symmetry``) acts on a V x V pattern as C -> T C T^T with
T = sum_x s(x) e_{g(x)} e_x^T. The orbit span of a set of patterns is closed under the generators; on it the group acts
by orthogonal matrices. Multiplicities of irreducible constituents follow from character inner products
<chi_A, chi_B> = (1/|G|) sum_g chi_A(g) chi_B(g) (real characters), and the characters of the symmetric powers
from the traces of powers of the representation matrices (Newton / cycle-index formulas).
"""

from __future__ import annotations

import numpy as np
import scipy.sparse as sps


def perm_matrix(g, s):
    V = len(g)
    return sps.csr_matrix((s, (g, np.arange(V))), shape=(V, V))


def act(T, C):
    return (T @ C @ T.T).tocsr()


def orbit_span(seed, Ts):
    """Orthonormal basis (columns: flattened V x V patterns) of the span of the orbit
    of ``seed`` under the generators."""
    vec = lambda C: C.toarray().reshape(-1)
    basis, mats = [], []

    def add(C):
        v = vec(C)
        if basis:
            B = np.array(basis)
            coef = np.linalg.lstsq(B.T, v, rcond=None)[0]
            if np.linalg.norm(B.T @ coef - v) < 1e-9 * max(1.0, np.linalg.norm(v)):
                return
        basis.append(v)
        mats.append(C)

    for C in seed:
        add(C)
    i = 0
    while i < len(mats):
        for T in Ts:
            add(act(T, mats[i]))
        i += 1
    return np.linalg.qr(np.array(basis).T)[0]


def representation(Q, T):
    """Matrix of C -> T C T^T on the span with orthonormal basis Q (asserted orthogonal: the span is G-closed)."""
    V = int(round(np.sqrt(Q.shape[0])))
    R = np.array(
        [Q.T @ act(T, sps.csr_matrix(Q[:, k].reshape(V, V))).toarray().reshape(-1) for k in range(Q.shape[1])]
    ).T
    assert abs(R.T @ R - np.eye(R.shape[1])).max() < 1e-9, "space not closed under G"
    return R


def group_representations(gens, spans):
    """Enumerate the group generated by ``gens`` = [(g, s)] (modulo the global sign of s) together with the
    representation matrices on each span: returns a list of tuples (R_span1, R_span2, ...) over the group elements."""
    V = len(gens[0][0])
    Ts = [perm_matrix(g, s) for g, s in gens]
    reps = [[representation(Q, T) for T in Ts] for Q in spans]
    key = lambda g, s: g.tobytes() + (s * s[0]).astype(np.int8).tobytes()
    ident = (np.arange(V), np.ones(V))
    elems = {key(*ident): (ident, tuple(np.eye(Q.shape[1]) for Q in spans))}
    queue = [key(*ident)]
    while queue:
        (g, s), Rs = elems[queue.pop()]
        for k, (tg, ts) in enumerate(gens):
            g2, s2 = tg[g], s * ts[g]
            k2 = key(g2, s2)
            if k2 not in elems:
                elems[k2] = ((g2, s2), tuple(rep[k] @ R for rep, R in zip(reps, Rs, strict=True)))
                queue.append(k2)
    return [Rs for _, Rs in elems.values()]


def power_traces(Rs, kmax):
    """[tr R^k for every element] for k = 1..kmax."""
    return [np.array([np.trace(np.linalg.matrix_power(R, k)) for R in Rs]) for k in range(1, kmax + 1)]


def sym_characters(p):
    """Characters of Sym^1, Sym^3, Sym^5 from the power traces p = [p1, ..., p5] (cycle-index formulas)."""
    p1, p2, p3, p4, p5 = p
    sym3 = (p1**3 + 3 * p1 * p2 + 2 * p3) / 6
    sym5 = (p1**5 + 10 * p1**3 * p2 + 15 * p1 * p2**2 + 20 * p1**2 * p3 + 20 * p2 * p3 + 30 * p1 * p4 + 24 * p5) / 120
    return p1, sym3, sym5
