"""Chain cases run with the notebook runners and with scripts/run_chain.py (same physics, same seeds).

Each case: (notebook runner, notebook arguments, clean arguments). The notebook runner writes one npz into
--out; the reference keeps its ts_ series and the final configuration.
"""

COMMON = ["--L", "4", "--kappa", "-0.01", "--ntherm", "4", "--ntraj", "6"]

CASES = {
    # epsilon model, stochastic and dense fermion estimators, plain and Hasenbusch/MTS integrators
    "eps_noise": ("run_scan.py", ["--y", "2.41"], ["--y", "2.41"]),
    "eps_exact": (
        "run_scan.py",
        ["--y", "3.0", "--exact-ferm", "--start", "afm"],
        ["--y", "3.0", "--exact", "--start", "afm"],
    ),
    "eps_hasenbusch": (
        "run_scan.py",
        ["--y", "2.41", "--hasenbusch", "0.05", "0.5", "--mts", "4", "2", "2"],
        ["--y", "2.41", "--hasenbusch", "0.05", "0.5", "--mts", "4", "2", "2"],
    ),
    # link fields of the completed term (wedge edge, interior, per-link model), complete 10/6-channel
    # estimator
    "wedge_noise": (
        "run_wedge.py",
        ["--y", "2.41", "--g10", "0.1", "--g6-rel", "1", "--chi10", "full", "--tau-jitter", "0.3"],
        ["--y", "2.41", "--g10", "0.1", "--g6", "0.1", "--measure", "channels", "--tau-jitter", "0.3"],
    ),
    "wedge_exact": (
        "run_wedge.py",
        [
            "--y",
            "2.41",
            "--g10",
            "0.05",
            "--g6",
            "0.02",
            "--chi10",
            "full",
            "--exact-ferm",
            "--start",
            "afm+dimer",
        ],
        [
            "--y",
            "2.41",
            "--g10",
            "0.05",
            "--g6",
            "0.02",
            "--measure",
            "channels",
            "--exact",
            "--start",
            "afm+dimer",
        ],
    ),
    "links": (
        "run_wedge.py",
        ["--y", "2.41", "--g10", "0.05", "--quads", "links", "--chi10", "full", "--start", "hot+hot"],
        ["--y", "2.41", "--g10", "0.05", "--quads", "links", "--measure", "channels", "--start", "hot+hot"],
    ),
    "wedge_hasenbusch": (
        "run_wedge.py",
        [
            "--y",
            "2.41",
            "--g10",
            "0.1",
            "--g6-rel",
            "1",
            "--chi10",
            "full",
            "--tau-jitter",
            "0.3",
            "--hasenbusch",
            "0.05",
            "0.5",
            "--mts",
            "4",
            "2",
        ],
        [
            "--y",
            "2.41",
            "--g10",
            "0.1",
            "--g6",
            "0.1",
            "--measure",
            "channels",
            "--tau-jitter",
            "0.3",
            "--hasenbusch",
            "0.05",
            "0.5",
            "--mts",
            "4",
            "2",
        ],
    ),
    # flavour-blind nodal same-parity source with the complete estimator
    "source_c0": (
        "run_wedge.py",
        [
            "--y",
            "2.41",
            "--g10",
            "0.05",
            "--g6-rel",
            "1",
            "--h10",
            "0.05",
            "--chi10",
            "full",
            "--tau-jitter",
            "0.3",
        ],
        [
            "--y",
            "2.41",
            "--g10",
            "0.05",
            "--g6",
            "0.05",
            "--h",
            "0.05",
            "--measure",
            "channels",
            "--tau-jitter",
            "0.3",
        ],
    ),
    # model N1: taste-chiral Majorana mass, all-antiperiodic box, dense and stochastic taste measures
    "n1_exact": (
        "run_wedge.py",
        [
            "--y",
            "3.0",
            "--g10",
            "0",
            "--h10",
            "0.5",
            "--h10-pattern",
            "chiral",
            "--bc",
            "aaaa",
            "--exact-ferm",
            "--tau-jitter",
            "0.3",
            "--store-cfgs",
            "--start",
            "afm+zero",
        ],
        [
            "--y",
            "3.0",
            "--h",
            "0.5",
            "--pattern",
            "chiral",
            "--bc",
            "aaaa",
            "--measure",
            "n1",
            "--exact",
            "--tau-jitter",
            "0.3",
            "--store-cfgs",
            "--start",
            "afm+zero",
        ],
    ),
    "n1_noise": (
        "run_wedge.py",
        [
            "--y",
            "2.41",
            "--g10",
            "0",
            "--h10",
            "1.0",
            "--h10-pattern",
            "chiral",
            "--bc",
            "aaaa",
            "--hasenbusch",
            "0.05",
            "0.5",
            "--mts",
            "4",
        ],
        [
            "--y",
            "2.41",
            "--h",
            "1.0",
            "--pattern",
            "chiral",
            "--bc",
            "aaaa",
            "--measure",
            "n1",
            "--hasenbusch",
            "0.05",
            "0.5",
            "--mts",
            "4",
        ],
    ),
    # flavour-selective nodal source on flavour 4 (|Pf| weight) with the Pfaffian sign
    "selective": (
        "run_wedge.py",
        [
            "--y",
            "2.41",
            "--g10",
            "0",
            "--h10",
            "0.2",
            "--h10-flavour",
            "4",
            "--exact-ferm",
            "--pf-sign",
            "inline",
            "--pf-sign-h",
            "0.5",
        ],
        [
            "--y",
            "2.41",
            "--h-sel",
            "0.2",
            "--flavours",
            "4",
            "--measure",
            "n1",
            "--exact",
            "--pf-sign",
            "--pf-sign-h",
            "0.5",
        ],
    ),
}
