"""Light corner-algebra invariants of the C_chi-sourced action on 4^4: assumption (A4) of the proposition (K5.14).

Every corner string X_S Z_D is built as a translation-covariant lattice bilinear (``mass_strings.string_op``, both site
symmetrisations; 496 of the 512 are non-zero) and averaged over three groups of signed site maps of K that fix C_chi:

  pg     the stabiliser of C_chi in the hypercubic point group (32 elements);
  pg+Z4  pg extended by the C_chi-flipping point-group elements composed with the Z4 generator chi -> i^eps(x) chi,
         which multiplies a bilinear with an even number of links by -1 (64 elements);
  all    the stabiliser in the group generated by the point group and the one-site shifts (8192 of 98304 elements).

A string survives a group when the light part of its group average, P_L Obar P_L or P_L Obar P_R, is non-zero. The
group averages under ``all`` are computed exactly as orbit averages under a generating set of the stabiliser (the
group acts transitively on the orbit, so the orbit mean is the group mean). Labels per string: kernel symmetry
(antisymmetric = flavour-symmetric Grassmann bilinear), taste (LL+RR if it commutes with the taste chirality Q, LR if it
anticommutes), parity in p at the corner (even: a cos, odd: a sin momentum factor), mass-type (anticommutes with K;
equivalently one of the 16 corner strings anticommuting with every Gamma_mu), and the number of Gamma_mu it
anticommutes with.

``sign_field_parity`` checks the lemma behind the L-independence of these averages: the BFS sign field of every
hypercubic site map is a function of x mod 2 on periodic boxes, and x mod 2 times (-1)^{#{mu in R: x_mu = 0}} on
all-antiperiodic boxes, R the reflected axes of the map.
"""

from __future__ import annotations

import random
import time

import numpy as np

from .. import symmetry as S
from ..lattice import Lattice, kinetic_matrix
from ..patterns import TasteProjector, chiral_mass, kinetic_gammas, pauli_string, scalar_mass_strings
from .mass_strings import string_op

TOL = 1e-10


def _axes(bits):
    return tuple(r for r in range(4) if bits >> r & 1)


def _bits(axes):
    return sum(1 << r for r in axes)


def _fixes(Cd, rows, cols, vals, g, s, sign=+1.0):
    """T_g C T_g^T = sign * C, tested on the non-zeros of C (a signed permutation preserves their number)."""
    return np.abs(Cd[g[rows], g[cols]] * s[rows] * s[cols] - sign * vals).max() < TOL


def _small_generating_set(elems, V, size, seed=0):
    rnd = random.Random(seed)
    pool = list(elems)
    rnd.shuffle(pool)
    gens = []
    for e in pool:
        gens.append(e)
        if len(S.closure(gens, V, max_size=size + 1)) == size:
            return gens
    raise RuntimeError("no generating set found")


def groups(lat, K, C):
    """pg stabiliser, pg flips, the full stabiliser (as a list) and a small generating set of it."""
    V = lat.V
    Cd = C.toarray()
    Cc = C.tocoo()
    rows, cols, vals = Cc.row, Cc.col, Cc.data
    G_pg = S.closure(S.generators(lat, K, translations=False), V)
    St_pg = [e for e in G_pg if _fixes(Cd, rows, cols, vals, *e)]
    Fl_pg = [e for e in G_pg if _fixes(Cd, rows, cols, vals, *e, sign=-1.0)]
    pg_gens = _small_generating_set(G_pg, V, len(G_pg))
    tr = S.generators(lat, K, translations=True)[len(S.generators(lat, K, translations=False)) :]
    G_all = S.closure(pg_gens + tr, V)
    St_all = [e for e in G_all if _fixes(Cd, rows, cols, vals, *e)]
    st_gens = _small_generating_set(St_all, V, len(St_all))
    return dict(G_pg=G_pg, St_pg=St_pg, Fl_pg=Fl_pg, G_all=G_all, St_all=St_all, st_gens=st_gens)


def orbit_average(O, gens):
    """Exact group average of O over the group generated by gens, via the orbit of O."""
    key = lambda A: (np.round(A, 8) + 0.0).tobytes()
    seen = {key(O): O}
    queue = [O]
    while queue:
        A = queue.pop()
        for g, s in gens:
            B = S.transform(A, g, s)
            k = key(B)
            if k not in seen:
                seen[k] = B
                queue.append(B)
    return sum(seen.values()) / len(seen), len(seen)


def weighted_average(O, elems, signs=None):
    acc = np.zeros_like(O)
    for k, (g, s) in enumerate(elems):
        acc += (1.0 if signs is None else signs[k]) * S.transform(O, g, s)
    return acc / len(elems)


def enumerate_box(bc, verbose=False):
    """All 496 non-zero corner-string bilinears on 4^4 with boundary conditions bc: labels and light survival."""
    t0 = time.time()
    lat = Lattice((4,) * 4, bc=bc)
    K = kinetic_matrix(lat)
    Kd = K.toarray()
    C = chiral_mass(lat)
    tp = TasteProjector(lat)
    Q, PL, PR = tp.dense(), tp.dense_PL(), tp.dense_PR()
    grp = groups(lat, K, C)
    # every element used commutes with P_L (so the light part of the average = the average of the light part)
    comm = max(np.abs(S.transform(PL, g, s) - PL).max() for g, s in grp["St_pg"] + grp["Fl_pg"] + grp["st_gens"])
    Gam = kinetic_gammas(4)
    mass16 = {(Sx, Dx) for Sx, Dx, _ in scalar_mass_strings(4)}
    z4 = None
    rows = []
    for Sb in range(16):
        for Db in range(16):
            Sax, Dax = _axes(Sb), _axes(Db)
            P = pauli_string(Sb, Db)
            n_anti_gamma = int(sum(np.allclose(P @ g + g @ P, 0) for g in Gam))
            for anti in (True, False):
                O = string_op(lat, Sax, Dax, anti)
                nO = np.linalg.norm(O)
                if nO < 1e-12:
                    continue
                comQ = np.abs(O @ Q - Q @ O).max() < 1e-12
                antiQ = np.abs(O @ Q + Q @ O).max() < 1e-12
                light = lambda A: (np.linalg.norm(PL @ A @ PL) + np.linalg.norm(PL @ A @ PR)) / nO
                pg = weighted_average(O, grp["St_pg"])
                z4 = [1.0] * len(grp["St_pg"]) + [-1.0 if len(Dax) % 2 == 0 else 1.0] * len(grp["Fl_pg"])
                pgz4 = weighted_average(O, grp["St_pg"] + grp["Fl_pg"], z4)
                al, orb = orbit_average(O, grp["st_gens"])
                inter = len(set(Sax) & set(Dax)) % 2
                rows.append(
                    dict(
                        S=Sax,
                        D=Dax,
                        anti=anti,
                        taste="LL+RR" if comQ else ("LR" if antiQ else "mixed"),
                        even_p=(inter == 1) if anti else (inter == 0),
                        mass_type=bool(np.abs(O @ Kd + Kd @ O).max() < 1e-12),
                        in16=(Sax, Dax) in mass16,
                        n_anti_gamma=n_anti_gamma,
                        light=light(O),
                        light_pg=light(pg),
                        light_pgz4=light(pgz4),
                        light_all=light(al),
                        orbit_all=orb,
                    )
                )
    info = dict(
        bc=bc,
        G_pg=len(grp["G_pg"]),
        St_pg=len(grp["St_pg"]),
        Fl_pg=len(grp["Fl_pg"]),
        G_all=len(grp["G_all"]),
        St_all=len(grp["St_all"]),
        n_gens=len(grp["st_gens"]),
        PL_commutes=comm,
        seconds=time.time() - t0,
    )
    if verbose:
        print(info, flush=True)
    return info, rows


def survivors(rows, key):
    return [r for r in rows if r["light"] > TOL and r[key] > TOL]


def corner_facts():
    """Corner-algebra identities of the two four-link strings and of the taste chirality."""
    G = kinetic_gammas(4)
    X02 = pauli_string(_bits((0, 2)), _bits((0, 1, 2, 3)))
    X13 = pauli_string(_bits((1, 3)), _bits((0, 1, 2, 3)))
    G5 = G[0] @ G[1] @ G[2] @ G[3]
    prop = lambda A, B: min(np.abs(A - B).max(), np.abs(A + B).max()) < 1e-12
    return dict(
        X02Z0123_anticommutes_all=all(np.allclose(X02 @ g + g @ X02, 0) for g in G),
        X02Z0123_prop_G0G1G2G3=prop(X02, G5),
        X02Z0123_symmetric=bool(np.allclose(X02, X02.T)),
        X13Z0123_commutes_all=all(np.allclose(X13 @ g - g @ X13, 0) for g in G),
        X13Z0123_symmetric=bool(np.allclose(X13, X13.T)),
        gamma_strings=[(_axes(sum(1 << r for r in range(mu))), (mu,)) for mu in range(4)],
    )


def sign_field_parity(shape, bc):
    """For every hypercubic site map of K on the box: is its sign field a function of x mod 2 (periodic), or x mod 2
    times (-1)^{#{mu in R: x_mu = 0}}, R the reflected axes (antiperiodic)? Returns counts."""
    import itertools

    lat = Lattice(shape, bc=bc)
    K = kinetic_matrix(lat)
    co = lat.coords.reshape(lat.d, lat.V)
    par = sum((co[mu] % 2) << mu for mu in range(lat.d))
    n_maps = n_par = n_bnd = 0
    for perm in itertools.permutations(range(lat.d)):
        for refl in itertools.product((1, -1), repeat=lat.d):
            g = S.site_map(lat, perm, refl)
            if g is None:
                continue
            s = S.sign_field(K, g)
            if s is None:
                continue
            n_maps += 1

            def is_parity_fn(f):
                return all(len(set(np.round(f[par == c], 12))) == 1 for c in range(1 << lat.d))

            if is_parity_fn(s):
                n_par += 1
                continue
            R = [mu for mu in range(lat.d) if refl[mu] == -1]
            b = np.prod([np.where(co[mu] == 0, -1.0, 1.0) for mu in R], axis=0) if R else np.ones(lat.V)
            if is_parity_fn(s * b):
                n_bnd += 1
    return dict(maps=n_maps, parity=n_par, parity_times_boundary=n_bnd)
