"""All corner-space Lorentz-scalar mass strings of the light doublet under the symmetry group of the h C_chi-sourced
action (K5.12).

``patterns.scalar_mass_strings(4)`` gives the 16 strings X_S Z_D anticommuting with every corner Gamma_mu: 10 with an
antisymmetric site kernel (a Grassmann bilinear with a symmetric flavour matrix: the 10 of SU(4), which contains
delta_ab) and 6 with a symmetric site kernel (an antisymmetric flavour matrix: the sextet Lambda^2(4) = (3,1) + (1,3) of
SO(4)). ``string_op`` builds each as the translation-covariant lattice bilinear with phase zeta_S(x) and displacement D
(boundary signs included). The light part of a string is P_L O P_L when it commutes with the taste charge Q (LL + RR)
and P_L O P_R + h.c. when it anticommutes (LR).

``box_table`` averages every string and its light part over three groups built from the signed site maps of K
(``symmetry``): the stabiliser of C_chi in the hypercubic point group ("pg"), the stabiliser in the group generated by
the point group and the one-site shifts ("all"), and the point-group stabiliser extended by the C_chi-flipping
elements composed with the Z4 generator chi(x) -> i^eps(x) chi(x), which multiplies every same-parity bilinear by -1
("pg+Z4"). ``flavour_invariants`` counts the invariants of a flavour group in 4 x 4 (and how many are symmetric).
"""

from __future__ import annotations

import time

import numpy as np

from .. import symmetry as S
from ..flavour import GAMMA, GAMMA2
from ..lattice import Lattice, kinetic_matrix, shift_table
from ..patterns import TasteProjector, chiral_mass, scalar_mass_strings

TOL = 1e-10
ONSITE = ((0, 1, 2, 3), ())
FOURLINK = ((0, 2), (0, 1, 2, 3))


def string_op(lat, Sax, Dax, antisym):
    """The translation-covariant lattice bilinear with phase string S and displacement support D (boundary signs
    included), antisymmetrised or symmetrised in the site indices."""
    V = lat.V
    co = lat.coords.reshape(lat.d, V)
    zeta = (-1.0) ** (sum(co[r] for r in Sax) % 2) if Sax else np.ones(V)
    j, w = shift_table(lat, [1 if mu in Dax else 0 for mu in range(lat.d)])
    O = np.zeros((V, V))
    O[np.arange(V), j] += zeta * w
    return (O - O.T) / 2 if antisym else (O + O.T) / 2


def avg_ratio(O, grp, signs=None):
    """‖(1/|G|) Σ_g sign_g T_g O T_gᵀ‖ / ‖O‖."""
    acc = np.zeros_like(O)
    for k, (g, s) in enumerate(grp):
        acc += (1.0 if signs is None else signs[k]) * S.transform(O, g, s)
    return float(np.linalg.norm(acc / len(grp)) / np.linalg.norm(O))


def flip_keep(O, grp):
    """(number of elements mapping O -> -O, number mapping O -> +O)."""
    f = k = 0
    for g, s in grp:
        Og = S.transform(O, g, s)
        f += bool(np.allclose(Og, -O, atol=1e-12))
        k += bool(np.allclose(Og, O, atol=1e-12))
    return f, k


def groups(lat, C):
    """Point-group stabiliser, its C_chi-flipping complement, the full stabiliser with shifts and its complement."""
    V = lat.V
    K = kinetic_matrix(lat)
    G_pg = S.closure(S.generators(lat, K, translations=False), V)
    G_all = S.closure(S.generators(lat, K, translations=True), V)
    flips = lambda G: [(g, s) for g, s in G if abs(S.transform(C, g, s) + C).max() < TOL]
    return dict(G_pg=G_pg, St_pg=S.stabiliser(G_pg, C), Anti_pg=flips(G_pg), G_all=G_all, St_all=S.stabiliser(G_all, C))


def box_table(shape, bc, h=0.5, verbose=True):
    """Every scalar mass string on one box: taste, light fraction, lift of the light zero modes, group averages."""
    t0 = time.time()
    lat = Lattice(shape, bc=bc)
    V = lat.V
    Kd = kinetic_matrix(lat).toarray()
    C = chiral_mass(lat, (0, 3), +1).toarray()
    tp = TasteProjector(lat, (0, 3), +1)
    Q, PL, PR = tp.dense(), tp.dense_PL(), tp.dense_PR()
    gr = groups(lat, C)
    G_pg, St_pg, Anti_pg, G_all, St_all = (gr[k] for k in ("G_pg", "St_pg", "Anti_pg", "G_all", "St_all"))
    Anti_all = [(g, s) for g, s in G_all if abs(S.transform(C, g, s) + C).max() < TOL]
    co = lat.coords.reshape(lat.d, V)
    odd = sum(int(sum(co[mu][g[0]] for mu in range(lat.d)) % 2) for g, s in St_all)
    box = dict(
        V=V,
        boundary=tp.n_boundary,
        G_pg=len(G_pg),
        St_pg=len(St_pg),
        G_all=len(G_all),
        St_all=len(St_all),
        Anti_all=len(Anti_all),
        St_all_odd_shift=odd,
        strings={},
    )
    M = Kd - h * C
    for Sax, Dax, anti in scalar_mass_strings(4):
        O = string_op(lat, Sax, Dax, anti)
        par = len(Dax) % 2
        comQ = bool(np.abs(O @ Q - Q @ O).max() < 1e-12)
        antiQ = bool(np.abs(O @ Q + Q @ O).max() < 1e-12)
        taste = "LL+RR" if comQ else ("LR" if antiQ else "mixed")
        X = M - 0.3 * O if anti else M + 1j * 0.3 * O
        sv = np.sort(np.sqrt(np.maximum(np.linalg.eigvalsh(X.conj().T @ X).real, 0)))
        OL = PL @ O @ PL if comQ else PL @ O @ PR + PR @ O @ PL
        z4 = [1.0] * len(St_pg) + [-1.0 if par == 0 else 1.0] * len(Anti_pg)
        box["strings"][str((Sax, Dax))] = dict(
            S=Sax,
            D=Dax,
            antisym=anti,
            parity=par,
            taste=taste,
            PL_frac=float(np.linalg.norm(PL @ O @ PL) / np.linalg.norm(O)),
            anticomm_K=float(np.abs(O @ Kd + Kd @ O).max()),
            light_lift=float(sv[0]),
            lift8=float(sv[7]),
            avg_pg=avg_ratio(O, St_pg),
            avg_all=avg_ratio(O, St_all),
            avg_pg_z4=avg_ratio(O, St_pg + Anti_pg, z4),
            avgL_pg=avg_ratio(OL, St_pg),
            avgL_all=avg_ratio(OL, St_all),
            avgL_pg_z4=avg_ratio(OL, St_pg + Anti_pg, z4),
            flip_keep_all=flip_keep(O, St_all),
        )
    for name, O in (("C_chi", C), ("C_asd(0,3)", chiral_mass(lat, (0, 3), -1).toarray())):
        box[name] = dict(avg_pg=avg_ratio(O, St_pg), avg_all=avg_ratio(O, St_all))
    if verbose:
        print(f"  [box {shape} {bc} done in {time.time() - t0:.0f} s]", flush=True)
    return box


def so4_generators():
    B = []
    for a in range(4):
        for b in range(a + 1, 4):
            A = np.zeros((4, 4))
            A[a, b], A[b, a] = 1, -1
            B.append(A)
    return B


def flavour_invariants(gens):
    """(number of invariant bilinear forms in 4 x 4, how many of them are symmetric) of the Lie algebra spanned by
    ``gens``; the antisymmetric ones are invariants in Lambda^2(4) (sextet masses the group allows)."""
    Mx = np.vstack([np.kron(A, np.eye(4)) + np.kron(np.eye(4), A) for A in gens])
    s = np.linalg.svd(Mx, compute_uv=False)
    null = np.linalg.svd(Mx)[2][np.sum(s > 1e-10) :]
    sym = sum(1 for v in null if np.allclose(v.reshape(4, 4), v.reshape(4, 4).T))
    return len(null), sym


def all_invariants():
    return {
        "so(4)": flavour_invariants(so4_generators()),
        "su(2)_sigma (GAMMA)": flavour_invariants(list(GAMMA)),
        "su(2)_hidden (GAMMA2)": flavour_invariants(list(GAMMA2)),
    }


BOXES = (((4,) * 4, (1,) * 4), ((4,) * 4, (-1,) * 4))


def box_label(shape, bc):
    return "x".join(map(str, shape)) + " " + "".join("a" if b == -1 else "p" for b in bc)


def compute(verbose=True):
    """The K5.12 table: both 4^4 boxes and the flavour invariants (about 14 min, single thread)."""
    out = {"boxes": {}}
    for shape, bc in BOXES:
        out["boxes"][box_label(shape, bc)] = box_table(shape, bc, verbose=verbose)
    out["flavour_invariants"] = all_invariants()
    return out


def flat(o, pre=""):
    """(path, float) pairs of every number in a nested dict/list (for live = frozen comparisons)."""
    if isinstance(o, dict):
        for k, v in o.items():
            yield from flat(v, f"{pre}/{k}")
    elif isinstance(o, list | tuple):
        for i, v in enumerate(o):
            yield from flat(v, f"{pre}/{i}")
    elif isinstance(o, bool | int | float | np.floating | np.integer):
        yield pre, float(o)
